// <auto-generated />
using System;
using Eshop.Supplier.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eshop.Supplier.Migrations
{
    [DbContext(typeof(MyShowDBContext))]
    [Migration("20211109094406_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Eshop.Supplier.Entities.Category", b =>
                {
                    b.Property<int>("CategroyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategroyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("CategroyId");

                    b.ToTable("Categroy");
                });

            modelBuilder.Entity("Eshop.Supplier.Entities.Item", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(5)
                        .HasColumnType("Char(5)");

                    b.Property<int>("CategroyId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("CategroyId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Eshop.Supplier.Entities.Item", b =>
                {
                    b.HasOne("Eshop.Supplier.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategroyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
